version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: php
    volumes:
      - ./:/code
  composer:
    image: composer:1.9
    container_name: composer
    working_dir: /code
    volumes:
      - ./:/code
    command: composer install --ignore-platform-reqs