version: '3.3'
services:
  web:
    image: nginx:latest
    #container_name: web
    ports:
      - '8080:80'
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - my-network
  php:
    image: php:7-fpm
    #container_name: php7-fpm
    volumes:
      - ./:/code
    networks:
      - my-network

networks:
  my-network: